name: alepha_digital_tracking
description: "A new Flutter project with OpenStreetMap integration."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  curved_navigation_bar: ^1.0.6
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  permission_handler: ^10.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/onboarding/
    - asset/auth/
